[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
NEXT_TELEMETRY_DISABLED = "1"
