import {
  Play,
  Pause,
  Loader2,
  Settings,
  Home,
  Plus,
  Sparkles,
  Wand2,
  type LucideIcon,
  Radio,
  Compass,
  Upload,
  Link,
  FileText,
  Headphones,
  Share2,
  Edit,
  Trash2,
  Menu,
  X,
  Check,
  AlertTriangle,
  AlertOctagon,
  CheckCircle,
  Clock,
  Mic,
  Save,
  Globe,
  Bot,
  Speaker,
  Users,
  ChevronRight,
  Volume2,
  Square,
  Webhook,
  Calendar,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Radio,
  home: Home,
  create: Plus,
  discover: Compass,
  upload: Upload,
  link: Link,
  text: FileText,
  channel: Radio,
  podcast: Headphones,
  play: Play,
  pause: Pause,
  share: Share2,
  edit: Edit,
  delete: Trash2,
  settings: Settings,
  menu: Menu,
  close: X,
  wand: Wand2,
  spinner: Loader2,
  check: Check,
  warning: AlertTriangle,
  error: AlertOctagon,
  success: CheckCircle,
  clock: Clock,
  audio: Mic,
  plus: Plus,
  trash: Trash2,
  save: Save,
  globe: Globe,
  bot: Bot,
  speaker: Speaker,
  users: Users,
  chevronRight: ChevronRight,
  volume2: Volume2,
  square: Square,
  sparkles: Sparkles,
  webhook: Webhook,
  calendar: Calendar,
} as const;
