import * as LucideIcons from 'lucide-react'

export const Icons = {
  ...LucideIcons,
  logo: LucideIcons.Radio,
  home: LucideIcons.Home,
  create: LucideIcons.Plus,
  discover: LucideIcons.Compass,
  upload: LucideIcons.Upload,
  link: LucideIcons.Link,
  text: LucideIcons.FileText,
  channel: LucideIcons.Radio,
  podcast: LucideIcons.Headphones,
  play: LucideIcons.Play,
  pause: LucideIcons.Pause,
  share: LucideIcons.Share2,
  edit: LucideIcons.Edit,
  delete: LucideIcons.Trash2,
  settings: LucideIcons.Settings,
  menu: LucideIcons.Menu,
  close: LucideIcons.X,
  spinner: LucideIcons.Loader2,
  check: LucideIcons.Check,
  warning: LucideIcons.AlertTriangle,
  error: LucideIcons.AlertOctagon,
  success: LucideIcons.CheckCircle,
  clock: LucideIcons.Clock,
  audio: LucideIcons.Mic,
  plus: LucideIcons.Plus,
  trash: LucideIcons.Trash2,
  save: LucideIcons.Save,
  globe: LucideIcons.Globe,
  bot: LucideIcons.Bot,
  speaker: LucideIcons.Speaker,
  users: LucideIcons.Users,
}
